"""currency as varchar

Revision ID: 37d46ba4eadc
Revises: b3c4d5e6f7a8
Create Date: 2026-04-29 19:03:45.327094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37d46ba4eadc'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'currency',
               existing_type=postgresql.ENUM('UYU', 'USD', 'EUR', name='currencycode'),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'currency',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('UYU', 'USD', 'EUR', name='currencycode'),
               existing_nullable=False)
    # ### end Alembic commands ###
