"""add commission to transactions

Revision ID: 3f6dde3ff6a0
Revises: 37d46ba4eadc
Create Date: 2026-05-02 14:21:13.180695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6dde3ff6a0'
down_revision: Union[str, Sequence[str], None] = '37d46ba4eadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('commission', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'commission')
    # ### end Alembic commands ###
