"""add households feature

Revision ID: 6d7e49ad28c9
Revises: a2b3c4d5e6f7
Create Date: 2026-04-03 02:29:19.298139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7e49ad28c9'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('split_type', sa.Enum('EQUAL', 'PROPORTIONAL', name='splittype'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'USED', 'EXPIRED', name='invitestatus'), nullable=False),
    sa.Column('used_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_invites_code'), 'household_invites', ['code'], unique=True)
    op.create_table('household_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='memberrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', name='memberstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_concept_user_category_name'), 'concepts', type_='unique')
    op.create_unique_constraint('uq_concept_user_name', 'concepts', ['user_id', 'name'])
    op.drop_constraint(op.f('concepts_category_id_fkey'), 'concepts', type_='foreignkey')
    op.drop_column('concepts', 'category_id')
    op.drop_index(op.f('ix_exchange_rates_user_id'), table_name='exchange_rates')
    op.alter_column('external_accounts', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_importaciones_fecha'), table_name='importaciones')
    op.drop_index(op.f('ix_importaciones_user_id'), table_name='importaciones')
    op.drop_index(op.f('ix_instalment_plans_user_id'), table_name='instalment_plans')
    op.add_column('transactions', sa.Column('household_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_transactions_import_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_instalment_plan_id'), table_name='transactions')
    op.drop_constraint(op.f('transactions_cuenta_origen_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'households', ['household_id'], ['id'], ondelete='SET NULL')
    op.drop_column('transactions', 'cuenta_origen_id')
    op.drop_column('transactions', 'referencia_transferencia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('referencia_transferencia', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('cuenta_origen_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_cuenta_origen_id_fkey'), 'transactions', 'accounts', ['cuenta_origen_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_transactions_instalment_plan_id'), 'transactions', ['instalment_plan_id'], unique=False)
    op.create_index(op.f('ix_transactions_import_hash'), 'transactions', ['import_hash'], unique=False)
    op.drop_column('transactions', 'household_id')
    op.create_index(op.f('ix_instalment_plans_user_id'), 'instalment_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_importaciones_user_id'), 'importaciones', ['user_id'], unique=False)
    op.create_index(op.f('ix_importaciones_fecha'), 'importaciones', ['fecha'], unique=False)
    op.alter_column('external_accounts', 'owner_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_exchange_rates_user_id'), 'exchange_rates', ['user_id'], unique=False)
    op.add_column('concepts', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('concepts_category_id_fkey'), 'concepts', 'categories', ['category_id'], ['id'])
    op.drop_constraint('uq_concept_user_name', 'concepts', type_='unique')
    op.create_unique_constraint(op.f('uq_concept_user_category_name'), 'concepts', ['user_id', 'category_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_table('household_members')
    op.drop_index(op.f('ix_household_invites_code'), table_name='household_invites')
    op.drop_table('household_invites')
    op.drop_table('households')
    # ### end Alembic commands ###
