"""add_is_system_to_concepts

Revision ID: 87a5e3655cd7
Revises: 7c9005695215
Create Date: 2026-03-24 20:44:27.113456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a5e3655cd7'
down_revision: Union[str, Sequence[str], None] = '7c9005695215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('is_system', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'is_system')
    # ### end Alembic commands ###
